package com.wantdo.erp.model;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.orderid
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.series
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private String series;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.category
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.num
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.amout
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    private String amout;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public OrderItem(Integer id, Integer orderid, String sku, String series, String category, Integer num, String amout) {
        this.id = id;
        this.orderid = orderid;
        this.sku = sku;
        this.series = series;
        this.category = category;
        this.num = num;
        this.amout = amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public OrderItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.orderid
     *
     * @return the value of order_item.orderid
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.orderid
     *
     * @param orderid the value for order_item.orderid
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku
     *
     * @return the value of order_item.sku
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku
     *
     * @param sku the value for order_item.sku
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.series
     *
     * @return the value of order_item.series
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.series
     *
     * @param series the value for order_item.series
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.category
     *
     * @return the value of order_item.category
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.category
     *
     * @param category the value for order_item.category
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.num
     *
     * @return the value of order_item.num
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.num
     *
     * @param num the value for order_item.num
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.amout
     *
     * @return the value of order_item.amout
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public String getAmout() {
        return amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.amout
     *
     * @param amout the value for order_item.amout
     *
     * @mbggenerated Mon Apr 04 15:17:54 CST 2016
     */
    public void setAmout(String amout) {
        this.amout = amout == null ? null : amout.trim();
    }
}