package com.wantdo.erp.model;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderid
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.outstock_date
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    private Date outstockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.platform
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.warehouse
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    private String warehouse;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public OrderInfo(Integer id, String orderid, Date outstockDate, String platform, String warehouse) {
        this.id = id;
        this.orderid = orderid;
        this.outstockDate = outstockDate;
        this.platform = platform;
        this.warehouse = warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public OrderInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderid
     *
     * @return the value of order_info.orderid
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderid
     *
     * @param orderid the value for order_info.orderid
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.outstock_date
     *
     * @return the value of order_info.outstock_date
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public Date getOutstockDate() {
        return outstockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.outstock_date
     *
     * @param outstockDate the value for order_info.outstock_date
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public void setOutstockDate(Date outstockDate) {
        this.outstockDate = outstockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.platform
     *
     * @return the value of order_info.platform
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.platform
     *
     * @param platform the value for order_info.platform
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.warehouse
     *
     * @return the value of order_info.warehouse
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.warehouse
     *
     * @param warehouse the value for order_info.warehouse
     *
     * @mbggenerated Mon Apr 04 18:02:16 CST 2016
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }
}